### ISSUE TITLE
How can I run with ROS2 nav2?

### ISSUE THREAD

**Issue by luvwinnie** [unitreerobotics/point_lio_unilidar#6]
I'm trying to use it with ROS2 humble nav2 framework. Is there any plan to make it compatible with ROS2?

Or the unitree_lidar_ros2 can be used with nav2?

**Comment by UNSaWEN** [comment]
try with this one
https://github.com/whyscience/Point-LIO/tree/ros2

**Comment by luvwinnie** [comment]
Thank you for telling me about it! Let me try about it...

**Comment by JCastel358** [comment]
@luvwinnie were you able to be successful in implementation?

**Comment by luvwinnie** [comment]
sorry for late reply.

I was busying on other deadline and now I'm back to try this.

I tried to build it but it seems like it shows the following message.
```
admin@ubuntu:/workspaces/isaac_ros-dev$ colcon build --packages-select point_lio
Starting >>> point_lio
--- stderr: point_lio
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


Current CPU archtecture: aarch64
CMake Warning (dev) at CMakeLists.txt:43 (find_package):
  Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
  are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at CMakeLists.txt:46 (find_package):
  By not providing "Findcatkin.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "catkin", but
  CMake did not find one.

  Could not find a package configuration file provided by "catkin" with any
  of the following names:

    catkinConfig.cmake
    catkin-config.cmake

  Add the installation prefix of "catkin" to CMAKE_PREFIX_PATH or set
  "catkin_DIR" to a directory containing one of the above files.  If "catkin"
  provides a separate development package or SDK, be sure it has been
  installed.


---
Failed   <<< point_lio [3.21s, exited with code 1]

Summary: 0 packages finished [5.54s]
```
Doesn't it use colcon instead of catkin?

**Comment by luvwinnie** [comment]
Okay, I'm able to build it.

Need to do these steps.

1. Install Livox-SDK2 with https://github.com/Livox-SDK/Livox-SDK2
2. Install https://github.com/Livox-SDK/livox_ros_driver2 
3. finally install with this repository.
    git clone https://github.com/whyscience/Point-LIO.git -b ros2

**Comment by luvwinnie** [comment]
Okay, I'm able to build it.

Need to do these steps.

Install Livox-SDK2 with https://github.com/Livox-SDK/Livox-SDK2
Install https://github.com/Livox-SDK/livox_ros_driver2
finally install with this repository.
git clone https://github.com/whyscience/Point-LIO.git -b ros2
